logging:
  level:
    root: INFO

spring:
  jpa:
    database: postgresql
  security:
    user:
      name: ${USER_NAME}
      password: ${USER_PASSWORD}

tmdb:
  url: https://api.themoviedb.org/3
  api-key: ${TMDB_API_KEY}
  language: de-DE

---

spring:
  profiles: local
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/flixd
    username: postgres
    password: mysecretpassword
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  security:
    user:
      name: user
      password: password
